version: '3.3'

volumes:
  postgres_volume:
  static_volume:
  media_volume:
  redoc_volume:

services:
  db:
    container_name: foodgram-db
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    container_name: foodgram-backend
    image: unexpectedpatronus/foodgram_backend:latest
    restart: always
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
      - redoc_volume:/app/docs

    env_file:
      - ../.env

  frontend:
    container_name: foodgram-frontend
    image: unexpectedpatronus/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-nginx
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
      - redoc_volume:/usr/share/nginx/html/api/docs/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
