version: '3.3'

volumes:
  postgres_volume:
  static_volume:
  media_volume:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    container_name: foodgram-backend
    image: unexpectedpatronus/foogram_backend:latest
    restart: always
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media/
    env_file:
      - ../.env

  frontend:
    container_name: foodgram-frontend
    image: unexpectedpatronus/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.23.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/etc/nginx/html/static/
      - media_volume:/etc/nginx/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
