version: '3.3'

volumes:
  postgres_volume:
  static_volume:
  media_volume:
  redoc_volume:

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file: .env

  backend:
    image: unexpectedpatronus/foodgram_backend:latest
    restart: always
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
      - redoc_volume:/app/docs

    env_file: .env

  frontend:
    image: unexpectedpatronus/foodgram_frontend:latest
    volumes:
      - static_volume:/app/result_build/

  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/mediafiles/
      - redoc_volume:/redocdoc/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
