# Generated by Django 3.2.16 on 2023-07-17 13:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#E26C2D', 'Завтрак'), ('#008000', 'Обед'), ('#7366BD', 'Ужин')], unique=True),
        ),
    ]
