# Generated by Django 3.2.20 on 2023-07-14 16:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230714_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=[('#E26C2D', 'Завтрак'), ('#008000', 'Обед'), ('#7366BD', 'Ужин')]),
        ),
    ]
