# Generated by Django 3.2.20 on 2023-07-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230715_1918'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='\nrecipes_ingredient_name is empty\n',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='\nrecipes_ingredient_measurement_unit is empty\n',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='\nrecipes_recipe_name is empty\n',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(('name__isnull', False), ('name__regex', '^\\S')), name='\nrecipes_ingredient_name is empty\n'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(('measurement_unit__isnull', False), ('measurement_unit__regex', '^\\S')), name='\nrecipes_ingredient_measurement_unit is empty\n'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('name__isnull', False), ('name__regex', '^\\S')), name='\nrecipes_recipe_name is empty\n'),
        ),
    ]
