# Generated by Django 3.2.20 on 2023-07-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230715_1929'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='\nrecipes_ingredient_name is empty\n',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='\nrecipes_ingredient_measurement_unit is empty\n',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='\nrecipes_recipe_name is empty\n',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(('name__length__gt', 0)), name='ingredient_name_should_not_be_empty'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(('measurement_unit__length__gt', 0)), name='measurement_unit_should_not_be_empty'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('name__length__gt', 0)), name='recipe_name_should_not_be_empty'),
        ),
    ]
