# Generated by Django 3.2.20 on 2023-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20230715_1935'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='ingredient_name_should_not_be_empty',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='measurement_unit_should_not_be_empty',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='recipe_name_should_not_be_empty',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(('name__isnull', False)), name='ingredient_name_should_not_be_empty'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(('measurement_unit__isnull', False)), name='measurement_unit_should_not_be_empty'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('name__isnull', False)), name='recipe_name_should_not_be_empty'),
        ),
    ]
