# Generated by Django 3.2.20 on 2023-07-15 17:27

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20230715_1938'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='ingredient_name_should_not_be_empty',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='measurement_unit_should_not_be_empty',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='recipe_name_should_not_be_empty',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Единица измерения ингредиента'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=[('#E26C2D', 'Завтрак'), ('#008000', 'Обед'), ('#7366BD', 'Ужин')], unique=True),
        ),
    ]
